package rules.beer;
dialect  "mvel"

import brewbuddy.models.Beer;
import brewbuddy.models.UserBeerLogger;
import brewbuddy.models.User;

global java.util.HashMap<Beer, Integer> recommendationMap;

rule "beerCep"
    when
        $user: User()
        Number(intValue > 4) from accumulate (
            $log: UserBeerLogger(user.getId() == $user.getId())
            over window: time(5d), sum($log.getId())
        )
    then
        System.out.println("ASD");
        recommendationMap.put($beer, recommendationMap.getOrDefault($beer, 0) + 1);
end
