package rules.beer;
dialect  "mvel"

import brewbuddy.models.Brewery;
import brewbuddy.models.Beer;
import brewbuddy.models.StringWrapper;
import brewbuddy.models.enums.BeerType;

global java.util.HashMap<Integer, Integer> filterMap;
global String param;


query belongsTo(String x, String y,String wantedclass)
    StringWrapper(x, y,wantedclass;)
    or
    (StringWrapper(z, y;) and belongsTo(x, z, wantedclass;))
end

rule "Brewery Filter"
agenda-group "beerFilter"
when
    belongsTo($beerId,param,"Beer";)
then
    filterMap.put(Integer.parseInt($beerId), ((Integer)filterMap.getOrDefault($beerId, 0)) + 1);
end








