package rules.filter;
import brewbuddy.models.Brewery;
import brewbuddy.models.Beer;
import brewbuddy.models.StringWrapper;
import brewbuddy.models.enums.BeerType;


query belongsTo(String x, String y,String wantedclass)
    StringWrapper(x, y,wantedclass;)
    or
    (StringWrapper(z, y;) and belongsTo(x, z,wantedclass;))
end

rule "backward"
when
    belongsTo($x,"1a","Beer";)
then
    System.out.println($x);
end




