package rules.template;
dialect  "mvel"

import brewbuddy.models.Beer;
import brewbuddy.models.Brewery;
import brewbuddy.models.User;
import brewbuddy.models.Festival;
import brewbuddy.models.UserBeerLogger;
import brewbuddy.models.FestivalCoupon;
import java.util.ArrayList;
import java.util.List;
import java.util.Comparator;
import java.util.Collections
import brewbuddy.models.enums.CouponType;


declare FestivalBeerLogger
    $festivalBeerLogger:UserBeerLogger
end

declare UserBeersAccumulated
    user:User
    drunkBeers:Integer
end

global java.util.ArrayList<FestivalCoupon> coupons;

rule "Filter Beers By Festival"
agenda-group "festivalCoupons"
salience 100
no-loop
    when
        Festival($breweries: breweries)
    then
        for (Brewery brewery: (ArrayList<Brewery>)$breweries ){
            for (Beer beer: brewery.getBeers()){
                insert(beer);
            }
        }
end


rule "Filter Logger By Festival Beers"
agenda-group "festivalCoupons"
salience 99
no-loop
    when
        $festivalBeer:Beer()
        $userBeers:UserBeerLogger( beer==$festivalBeer)
    then
        insert(new FestivalBeerLogger($userBeers));
end


rule "Accumulate Drunk Beers By Users"
agenda-group "festivalCoupons"
salience 98
no-loop
    when
        $user:User()
        $drunkBeers: Number() from accumulate(FestivalBeerLogger($user==$festivalBeerLogger.getUser()),
                                              count(1))
    then
       UserBeersAccumulated accumulatedValues=new UserBeersAccumulated();
       accumulatedValues.setUser($user);
       accumulatedValues.setDrunkBeers($drunkBeers.intValue());
       insert(accumulatedValues);
end

rule "Sort By Drunken Beers"
agenda-group "festivalCoupons"
salience 97
no-loop
    when
        $festival:Festival()
        $usersBeers:List( size > 0 ) from collect( UserBeersAccumulated() )
    then
        Collections.sort($usersBeers, new Comparator<UserBeersAccumulated>() {
                public int compare(UserBeersAccumulated p1, UserBeersAccumulated p2) {
                    return Integer.compare(p1.getDrunkBeers(), p2.getDrunkBeers())*-1;
                }
        });
        for( int i=0;i<$usersBeers.size();i++){
            FestivalCoupon coupon=new FestivalCoupon();
                            coupon.setUser(((UserBeersAccumulated)$usersBeers.get(i)).getUser());
                            coupon.setType(CouponType.FESTIVAL);
                            coupon.setFestival($festival);
            if (i<1){
                coupon.setDiscountPercentage(100);
            }
            if (i>=1 && i<5){
                coupon.setDiscountPercentage(50);
            }
                coupons.add(coupon);
        }
end




